apiVersion: v1
kind: Service
metadata:
  # Same as file name
  name: client-cluster-ip-svc
spec:
  # Can be Ingres, NodePort etc..
  type: ClusterIP
  selector:
    # The object that this is selecting.
    component: web
  ports:
  - port: 3000
    targetPort: 3000
