apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  # Specify the access mode of nodes to the pvc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
