apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  storageClassName: manual
  # Specify the access mode of nodes to the pvc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
