apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
      - name: server
        image: jmgarcia214/multi-server
        #resources:
          #limits:
            #memory: "128Mi"
            #cpu: "500m"
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: application-config-map
          - secretRef:
              name: application-secret
        # Same with env From secret value is still displayed
        #env:
        #  - name: PGPASSWORD
        #    valueFrom:
        #        secretKeyRef:
        #          name: application-secret
        #          key: PGPASSWORD

